export const AppRoutes = {
    HOME: "home",
    LOGIN: "login",
    REGISTER: "register",
    AUTH_CALLBACK: "auth_callback",
    AUTH_2FA: "auth_2fa",
    FORGOT_PASSWORD: "forgot_password",
    RESET_PASSWORD: "reset_password",
    VERIFY_EMAIL_SUCCESS: "verify_email_success",
    VERIFY_EMAIL_ERROR: "verify_email_error",
    CATEGORY: "category",
    TAG: "tag",
    BESTSELLERS: "bestsellers",
    PRODUCT: "product",
    SEARCH: "search",
    CART: "cart",
    CHECKOUT: "checkout",
    CHECKOUT_RESULT: "checkout_result",
    ORDER: "order",
    SETTINGS_ORDERS: "settings_orders",
    SETTINGS_SECURITY: "settings_security",
    SETTINGS_ADDRESS: "settings_address",
    SETTINGS_NOTIFICATIONS: "settings_notifications",
    NOT_FOUND: "not_found",
} as const;

type AppRoutes = (typeof AppRoutes)[keyof typeof AppRoutes];

export const routePaths: Record<AppRoutes, string> = {
    [AppRoutes.HOME]: "/:lng",
    [AppRoutes.LOGIN]: "/:lng/login",
    [AppRoutes.REGISTER]: "/:lng/register",
    [AppRoutes.AUTH_CALLBACK]: "/:lng/oauth",
    [AppRoutes.AUTH_2FA]: "/:lng/two-factor",
    [AppRoutes.FORGOT_PASSWORD]: "/:lng/forgot-password",
    [AppRoutes.RESET_PASSWORD]: "/:lng/reset-password",
    [AppRoutes.VERIFY_EMAIL_SUCCESS]: "/:lng/verify-email-success",
    [AppRoutes.VERIFY_EMAIL_ERROR]: "/:lng/verify-email-error",
    [AppRoutes.CATEGORY]: "/:lng/category/:slug",
    [AppRoutes.TAG]: "/:lng/tag/:slug",
    [AppRoutes.BESTSELLERS]: "/:lng/bestsellers",
    [AppRoutes.PRODUCT]: "/:lng/product/:slug",
    [AppRoutes.SEARCH]: "/:lng/search",
    [AppRoutes.CART]: "/:lng/cart",
    [AppRoutes.CHECKOUT]: "/:lng/checkout",
    [AppRoutes.CHECKOUT_RESULT]: "/:lng/checkout/result",
    [AppRoutes.ORDER]: "/:lng/order/:id",
    [AppRoutes.SETTINGS_ORDERS]: "/:lng/settings/orders",
    [AppRoutes.SETTINGS_SECURITY]: "/:lng/settings/security",
    [AppRoutes.SETTINGS_ADDRESS]: "/:lng/settings/address",
    [AppRoutes.SETTINGS_NOTIFICATIONS]: "/:lng/settings/notifications",

    // last
    [AppRoutes.NOT_FOUND]: "*",
};
